export const catBreeds = {
  abyssinian: "abys",
  aegean: "aege",
  "american bobtail": "abob",
  "american curl": "acur",
  "american shorthair": "asho",
  "american wirehair": "awir",
  "arabian mau": "amau",
  "australian mist": "amis",
  balinese: "bali",
  bambino: "bamb",
  bengal: "beng",
  birman: "birm",
  bombay: "bomb",
  "british longhair": "bslo",
  "british shorthair": "bsho",
  burmese: "bure",
  burmilla: "buri",
  "california spangled": "cspa",
  "chantilly-tiffany": "ctif",
  chartreux: "char",
  chausie: "chau",
  cheetoh: "chee",
  "colorpoint shorthair": "csho",
  "cornish rex": "crex",
  cymric: "cymr",
  cyprus: "cypr",
  "devon rex": "drex",
  donskoy: "dons",
  "dragon li": "lihu",
  "egyptian mau": "emau",
  "european burmese": "ebur",
  "exotic shorthair": "esho",
  "havana brown": "hbro",
  himalayan: "hima",
  "japanese bobtail": "jbob",
  javanese: "java",
  "khao manee": "khao",
  korat: "kora",
  kurilian: "kuri",
  laperm: "lape",
  "maine coon": "mcoo",
  malayan: "mala",
  manx: "manx",
  munchkin: "munc",
  nebelung: "nebe",
  "norwegian forest cat": "norw",
  ocicat: "ocic",
  oriental: "orie",
  persian: "pers",
  "pixie-bob": "pixi",
  ragamuffin: "raga",
  ragdoll: "ragd",
  "russian blue": "rblu",
  savannah: "sava",
  "scottish fold": "sfol",
  "selkirk rex": "srex",
  siamese: "siam",
  siberian: "sibe",
  singapura: "sing",
  snowshoe: "snow",
  somali: "soma",
  sphynx: "sphy",
  tonkinese: "tonk",
  toyger: "toyg",
  "turkish angora": "tang",
  "turkish van": "tvan",
  "york chocolate": "ycho",
};

export function getBreedIdFromName(name) {
  if (!name) return null;
  const key = name.toLowerCase().trim();
  return catBreeds[key] || null;
}
